#!/usr/bin/env python2.7

import re
import sys
import math
import urllib2
import ConfigParser

from os import popen, path, getuid

CURR_FILE = path.realpath(__file__)
CURR_DIR = path.dirname(CURR_FILE)

IP_DIR = '/etc/ppp'
IP_SCRIPT_CONTENT = '''\
#!/usr/bin/env python2.7

import sys
import os

if __name__ == '__main__':
    gateway = os.environ['IPREMOTE']
    cmd = '/etc/ppp/ip-route {} ' + gateway
    try:
        os.system(cmd)
        sys.exit(0)
    except Exception:
        sys.exit(1)
'''


def _exec_cmd(cmd):
    return popen(cmd).readline()[:-1]


def _get_array(s):
    return s.replace(' ', '').split(',') if s else []


def _get_local_gateway():
    cmd = r'/usr/sbin/netstat -nr | ' \
          r'grep "^default.*en0" | ' \
          r'sed "s;^default *\([0-9\.]*\) .*$;\1;"'
    return _exec_cmd(cmd)


def _load_ini():
    cf = ConfigParser.ConfigParser()
    cf.read(path.join(CURR_DIR, 'ip-route.ini'))

    ini = {}
    for section in cf.sections():
        ini[section] = {
            'name': section,
            'server': _get_array(cf.get(section, 'server')),
            'gateway': _get_array(cf.get(section, 'gateway')),
            'routing': cf.get(section, 'routing'),
            'segment': _get_array(cf.get(section, 'segment')),
            'segment_file': _get_array(cf.get(section, 'segment_file'))
        }
    return ini


def _load_conf_by_name(name):
    return _load_ini().get(name, None)


def _load_conf_by_gateway(gateway):
    for name, conf in _load_ini().iteritems():
        if gateway in conf['gateway']:
            return conf
    return None


def _get_segments(conf):
    segs = conf['segment']

    for segfile in conf['segment_file']:
        if segfile[0] != '/':
            segfile = path.join(CURR_DIR, segfile)
        with open(segfile) as f:
            while True:
                seg = f.readline().strip()
                if not seg:
                    break
                if seg[0] == '#':
                    continue
                segs.append(seg)

    return segs


def ip_up(gateway):
    conf = _load_conf_by_gateway(gateway)
    if not conf:
        return

    if conf['routing'] == 'local':
        gateway = _get_local_gateway()

    cmd = ''
    for seg in _get_segments(conf):
        cmd += '/sbin/route add {} {}\n'.format(seg, gateway)

    _exec_cmd(cmd)


def ip_down(gateway):
    conf = _load_conf_by_gateway(gateway)
    if not conf:
        return

    cmd = ''
    for seg in _get_segments(conf):
        cmd += '/sbin/route delete {}\n'.format(seg)

    _exec_cmd(cmd)


def ip_install():
    # Empty IP_DIR
    _exec_cmd('rm -rf {}/*'.format(IP_DIR))

    ip_route = path.join(IP_DIR, 'ip-route')
    ip_route_ini = path.join(IP_DIR, 'ip-route.ini')

    # Copy file to IP_DIR
    cmd = 'cp -f {0}/{1} {2}'
    _exec_cmd(cmd.format(CURR_DIR, 'ip-route', ip_route))
    _exec_cmd(cmd.format(CURR_DIR, 'ip-route.ini.sample', ip_route_ini))

    ip_up = path.join(IP_DIR, 'ip-up')
    ip_down = path.join(IP_DIR, 'ip-down')

    # Generate new ip-up / ip-down
    with open(ip_up, 'w') as fu, open(ip_down, 'w') as fd:
        fu.write(IP_SCRIPT_CONTENT.format('up'))
        fd.write(IP_SCRIPT_CONTENT.format('down'))

    # Set execute permission
    _exec_cmd('chmod a+x {} {} {}'.format(ip_up, ip_down, ip_route))


def ip_uninstall():
    # Empty IP_DIR
    _exec_cmd('rm -rf {}/*'.format(IP_DIR))


######
# Reference:
# https://github.com/fivesheep/chnroutes
###
def ip_fetch_gfw_segment():
    # Fetch data from apnic
    print 'Fetching data from apnic.net, please wait...'
    url = r'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest'
    data = urllib2.urlopen(url).read()

    cnregex = re.compile(r'apnic\|cn\|ipv4\|[0-9\.]+\|[0-9]+\|[0-9]+\|a.*',
                         re.IGNORECASE)
    cndata = cnregex.findall(data)

    results = []

    for item in cndata:
        unit_items = item.split('|')
        starting_ip = unit_items[3]
        num_ip = int(unit_items[4])

        imask = 0xffffffff ^ (num_ip - 1)

        # Convert to string
        imask = hex(imask)[2:]
        mask = [0]*4
        mask[0] = imask[0:2]
        mask[1] = imask[2:4]
        mask[2] = imask[4:6]
        mask[3] = imask[6:8]

        # Mask in *nix format
        mask = 32 - int(math.log(num_ip, 2))

        results.append('{}/{}'.format(starting_ip, mask))

    segfile = path.join(CURR_DIR, 'segment_gfw')
    with open(segfile, 'w') as f:
        f.write('\n'.join(results))

    print 'Done... Save to segment_gfw.'


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit('Execution FAILED: missing argument')

    op = sys.argv[1]
    fn = 'ip_{}'.format(op)

    if op == 'up' or op == 'down':
        if len(sys.argv) < 3:
            sys.exit('Execution FAILED: missing argument')
        locals()[fn](sys.argv[2])

    if op == 'install' or op == 'uninstall':
        if getuid() != 0:
            sys.exit('Execution FAILED: Must be root')
        locals()[fn]()

    if op == 'fetch_gfw_segment':
        ip_fetch_gfw_segment()
